<?php

return [
    'adminEmail' => 'admin@example.com',
	'appid' =>'wx05a87acdc3d63406',
	'secret' => '1eca4c9c03b8e32490c68f90b9977901',
	'token'=>'weixin',
	'reflashtime'=>3600,
	'memcacheKey'=>'AccessToken',
	'menu_data'=>'
		{
	     "button":[
	     {  
	          "name":"登录",
	          "sub_button":[
	          {
	            "type":"click",
	            "name":"第一种方法",
	            "key":"key1" 
	          },
	          {
	            "type":"view",
	            "name":"第二种方法",
	            "url":"http://www.baidu.com" 
	          },
	          {
	            "type":"view",
	            "name":"dota2",
	            "url":"http://www.dota2.com.cn" 
	          },
	          {
	            "type":"view",
	            "name":"youku",
	            "url":"http://www.youku.com"  
	          }]
	      },
	      {
	          "name":"测试用",    
	          "sub_button":[
	          {
	            "type":"click",
	            "name":"测试1",
	            "key":"key2"
	          },
	          {
	            "type":"click",
	            "name":"测试2",
	            "key":"key3"
	          },
	          {
	            "type":"click",
	            "name":"测试3",
	            "key":"key4"
	          },
	          {
	            "type":"click",
	            "name":"我的积分",
	            "key":"wodejifen"
	          },
	          {
	            "type":"click",
	            "name":"签到",
	            "key":"shangjiaqiandao"
	          }]
	      },
	      {
	           "name":"关于我们",
	           "sub_button":[
	           {  
	               "type":"view",
	               "name":"QQ1",
	               "url":"http://www.qq.com"
	            },
	            {
	               "type":"view",
	               "name":"baidu1",
	               "url":"http://www.baidu.com"
	            }]
	       }]
	 }',
];
